name: My First Workflow
on: push
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - name: just a simple ls command
        run: ls -la
      
      
      
      
